# Authors: Andrei Variu Oct 2022 (andrei.variu@epfl.ch), Shadab Alam Nov 2021

# Generate lightcone for DESI mocks
# from HOD catalogues generated by Shadab

import argparse
import os
from generate_light_cone_hf import LightCone, Paths
from apply_survey_geometry import SurveyGeometry

from stack_shells_into_fits_hf import stack_shells


def cutsky_ic_ABACUS(args, galtype=None, redshift=None, snapshot=None):
    in_fol_temp = "AbacusSummit_base_c000_ph"
    if galtype == 'LRG':
        config_file = f"./ABACUS/config/config_ABACUS_ic_LRG.ini"
    elif galtype == 'ELG':
        config_file = f"./ABACUS/config/config_ABACUS_ic_ELG.ini"
    elif galtype == 'QSO':
        config_file = f"./ABACUS/config/config_ABACUS_ic_QSO.ini"

    ######### Instances
    lightcone_instance = LightCone(config_file, args)
    # survey_geometry_instance = SurveyGeometry(config_file, args, galtype=galtype)

    # ######### CutSky
    for i in range(0, 1):
        phase = str(int(i)).zfill(3)

        in_part_path = "{redshift}/" + f"/{in_fol_temp}{phase}/"
        input_name = "ic_dens_576_SB{subbox}.fits"

        out_part_path = f"/{redshift}/{in_fol_temp}{phase}/"		
        output_name = "ic_snap{snapshot}_ph" + phase + "_shell_{shellnum}.hdf5"

        path_instance = Paths(config_file, args, in_part_path, input_name, out_part_path, output_name, phase=phase)

        lightcone_instance.generate_shells(path_instance, snapshot=snapshot, redshift=redshift, cutsky=True, nproc=6, n_subboxes=64, cat_seed=i)

        survey_geometry_instance.shell(path_instance, nproc=64, todo=3)

        out_fits = path_instance.dir_out + f"/{redshift}/fits/cutsky_{galtype}_{redshift}_{in_fol_temp}{phase}.fits"
        stack_shells(survey_geometry_instance, inpath=path_instance.shells_out_path, out_file=out_fits, mock_random_ic="mock", ngc_sgc_tot="TOT", seed=i)

def cutsky_ABACUS_HF(args, galtype=None, gal_in_name=None, redshift=None):
    cpus = int(os.environ.get("SLURM_CPUS_PER_TASK", 6))
    config_file = f"./ABACUS/config/config_ABACUS_{galtype}_HFDR2.ini"
    in_fol_temp = "AbacusSummit_base_c000_ph"

    ######### Instances
    lightcone_instance = LightCone(config_file, args)
    survey_geometry_instance = SurveyGeometry(config_file, args, galtype=galtype)

    # ######### CutSky
    for i in range(1):
        phase = str(int(i)).zfill(3)

        in_part_path = "{redshift}/" #+ f"/{in_fol_temp}{phase}/"
        input_name = gal_in_name + "_real_space.sub{subbox}.fits.gz"


        out_part_path = f"/{redshift}/{in_fol_temp}{phase}/"		
        output_name = gal_in_name + "_ph" + phase + "_shell_{shellnum}.hdf5"

        path_instance = Paths(config_file, args, in_part_path, input_name, out_part_path, output_name, phase=phase)

        lightcone_instance.generate_shells(path_instance, redshift=redshift, cutsky=True, nproc=cpus, n_subboxes=64, cat_seed=i, phase=phase)

        survey_geometry_instance.shell(path_instance, nproc=cpus, todo=3)
        ##survey_geometry_instance.shell_series(path_instance, todo=3)

        out_fits = path_instance.dir_out + f"/{redshift}/cutsky_{galtype}_{redshift}_{in_fol_temp}{phase}.fits"
        
        stack_shells(survey_geometry_instance, inpath=path_instance.shells_out_path, out_file=out_fits, mock_random_ic="mock", ngc_sgc_tot="TOT", seed=i)




def main():
    parser = argparse.ArgumentParser()
    # parser.add_argument("config", help="ini file holding configuration", type=str)
    parser.add_argument("--dir_out", type=str, help="output directory (overrides config file)")
    parser.add_argument("--dir_in", type=str, help="input directory (same)")
    parser.add_argument("--input_name", type=str, help="name of input catalogs (same)")
    parser.add_argument("--galaxy", type=str, help="LRG QSO ELG")
    parser.add_argument("--phase", type=int, help="phase of the catalog")
    parser.add_argument("--ngc_sgc", type=str, help="NGC or SGC preferred rotation")
    parser.add_argument("--mock_random_ic", type=str, help="mock, random or ic")

    args = parser.parse_args()

    import time
    start = time.time()

    cutsky_ABACUS_HF(args, galtype="LRG", gal_in_name="LRG",        redshift="z0.500")
    cutsky_ABACUS_HF(args, galtype="LRG", gal_in_name="LRG",        redshift="z0.725")
    cutsky_ABACUS_HF(args, galtype="LRG", gal_in_name="LRG",        redshift="z0.950")
    #cutsky_ABACUS_HF(args, galtype="ELG", gal_in_name="ELG",        redshift="z0.950")
    cutsky_ABACUS_HF(args, galtype="ELG", gal_in_name="ELG",        redshift="z1.175")
    cutsky_ABACUS_HF(args, galtype="ELG", gal_in_name="ELG",        redshift="z1.475")
    cutsky_ABACUS_HF(args, galtype="QSO", gal_in_name="QSO",        redshift="z1.400")


    end = time.time()
    print(f"################## FINISHED in {end-start}")


if __name__ == '__main__':
    main()
