# Authors: Andrei Variu Oct 2022 (andrei.variu@epfl.ch), Shadab Alam Nov 2021

# Generate lightcone for DESI mocks
# from HOD catalogues generated by Shadab

import argparse
import os
from generate_light_cone_home import LightCone, Paths
from apply_survey_geometry import SurveyGeometry

from stack_shells_into_fits_home import stack_shells



def cutsky_HOME(args, galtype=None, gal_in_name=None, redshift=None, cosmo='000', phas=None):
    cpus = int(os.environ.get("SLURM_CPUS_PER_TASK", 6))
    config_file = f"./HOME/config/config_HOME_{galtype}_DR2.ini"
    

    ######### Instances
    survey_geometry_instance = SurveyGeometry(config_file, args, galtype = galtype)


    input_name = gal_in_name + "_real_space.sub{subbox}.fits.gz"


    out_part_path = f"{gal_in_name}/temp/"		
    output_name = gal_in_name +  "_shell_{shellnum}.hdf5"

    path_instance = Paths(config_file, args, input_name, out_part_path, output_name, phase=phas, cosmo=cosmo)
    lightcone_instance = LightCone(config_file, args, cosmoprimo=path_instance.return_cosmoprimo(), cosmo=cosmo)
    #TEMPlightcone_instance.generate_shells(path_instance, redshift=redshift, cutsky=True, nproc=cpus, n_subboxes=64, cat_seed=1, phase=phas)

    #TEMPsurvey_geometry_instance.shell(path_instance, nproc=cpus, todo=3)
    #survey_geometry_instance.shell_series(path_instance, todo=3)

    out_fits = path_instance.dir_out + f"cutsky_{galtype}_zrsd.fits"
        
    stack_shells(survey_geometry_instance, inpath=path_instance.shells_out_path, out_file=out_fits, mock_random_ic="mock", ngc_sgc_tot="TOT", seed=10)




def main():

    parser = argparse.ArgumentParser()
    # parser.add_argument("config", help="ini file holding configuration", type=str)
    parser.add_argument("--dir_out", type=str, help="output directory (overrides config file)")
    parser.add_argument("--dir_in", type=str, help="input directory (same)")
    parser.add_argument("--input_name", type=str, help="name of input catalogs (same)")
    parser.add_argument("--galaxy", type=str, help="LRG QSO ELG")
    parser.add_argument("--phase", type=int, help="phase of the catalog")
    parser.add_argument("--ngc_sgc", type=str, help="NGC or SGC preferred rotation")
    parser.add_argument("--mock_random_ic", type=str, help="mock, random or ic")

    args = parser.parse_args()

    import time
    start = time.time()


    cutsky_HOME(args, galtype="LRG", gal_in_name="LRG", cosmo='000')
    


    end = time.time()
    print(f"################## FINISHED in {end-start}")


if __name__ == '__main__':
    main()
