[dir]
;dir_out                         = /global/cfs/projectdirs/desi/mocks/cai/abacus_HF/DR2_v1.0/AbacusSummit_base_c000_ph{phase}/CutSky/QSO/
;dir_in                          = /global/cfs/projectdirs/desi/mocks/cai/abacus_HF/DR2_v1.0/AbacusSummit_base_c000_ph{phase}/Boxes/QSO/
dir_in				= /global/cfs/projectdirs/desi/mocks/cai/abacus_HF/DR2_v1.0/alternative_cosmologies/AbacusSummit_base_c{cosmo}_ph{phase}/Boxes/QSO/
dir_out				= /pscratch/sd/a/acarnero/codes/desi-cutsky-mock/ABACUS/config/AbacusSummit_base_c{cosmo}_ph{phase}/CutSky/QSO/

file_camb                       = ./ABACUS/params_Abacus_cosmo000.ini
file_alist                      = ./ABACUS/steps/ABACUS_steps_QSO.txt

[nz]
downsample                   = ./nz_files/HighFidelity/NZ_QSO_v3.txt

col_z  = 0
col_nz = 1

downsample_red_cor           = ./nz_files/NZ_QSO_redcor_HFv3.dat

[failurerate]
downsample                    = 0.

[sim]
box_length      = 2000
shellwidth      = 25 
zmin            = 0.55
zmax            = 4.5
ngc_sgc         = NGC
rotate          = False
mock_random_ic  = mock
